Repository najasin/na-jasin-fe, pull requests merged in 2023-08, with the labels that each got.

#24 Prettier Setting 수정
  .prettierrc.js
Labels: hotfix

#27 공통 컴포넌트 - CommonBtn 구현
  app/tina/page.tsx
  components/commonBtn/CommonBtn.module.scss
  components/commonBtn/CommonBtn.tsx
  components/commonBtn/commonBtn.types.ts
  next.config.js
  styles/_mixin.scss
  styles/_variables.scss
Labels: feature

#26 hotfixstorybook path 수정
  .storybook/main.ts
Labels: hotfix

#31 CircleButton 수정
  components/fab/circleButton.module.scss
  components/fab/circleButton.tsx
  components/fab/circleButton.types.ts
Labels: feature

#37 skyblue-point 색상 추가
  styles/_variables.scss
Labels: hotfix

#35 CircleButton Story 작성
  components/fab/circleButton.stories.ts
Labels: feature

#33 chromatic 설정
  .github/workflows/chromatic.yml
  .gitignore
  build-storybook.log
  package-lock.json
  package.json
  scripts/chromatic_publish.sh
Labels: chore

#41 Typograpy 파일 추가 및 mixin, localFont 설정
  .prettierrc.js
  public/fonts/GmarketSansBold.woff
  public/fonts/GmarketSansLight.woff
  public/fonts/GmarketSansMedium.woff
  public/fonts/HSYuji.woff
  styles/_mixin.scss
  styles/local.fonts.ts
Labels: chore

#42 공통 컴포넌트 - Input 제작
  components/commonInput/input.module.scss
  components/commonInput/input.stories.tsx
  components/commonInput/input.tsx
  components/commonInput/input.types.ts
  components/commonInput/inputTextField.stories.tsx
  styles/local.fonts.ts
Labels: feature

#44 Radar 컴포넌트 제작
  app/layout.tsx
  components/radarChart/defaultPolygon.stories.ts
  components/radarChart/draggablePolygon.stories.ts
  components/radarChart/radarChart.helpers.ts
  components/radarChart/radarChart.module.scss
  components/radarChart/radarChart.tsx
  components/radarChart/radarChart.types.ts
  components/radarChart/radarChartContainer.stories.ts
  components/radarChart/radarChartContainer.tsx
  package-lock.json
  package.json
Labels: feature

#49 공통컴포넌트 - simpleLayout 구현
  app/tina/page.tsx
  components/commonBtn/commonBtn.module.scss
  components/commonBtn/commonBtn.stories.ts
  components/commonBtn/commonBtn.tsx
  components/simpleLayout/layoutBtn.module.scss
  components/simpleLayout/layoutBtn.stories.ts
  components/simpleLayout/layoutBtn.tsx
  components/simpleLayout/layoutBtn.types.ts
  components/simpleLayout/simpleLayout.module.scss
  components/simpleLayout/simpleLayout.stories.ts
  components/simpleLayout/simpleLayout.tsx
  components/simpleLayout/simpleLayout.types.ts
  public/images/arrow.svg
  public/images/logo.png
Labels: feature

#51 공통 컴포넌트 - item box 구현
  components/itemBox/itemBox.module.scss
  components/itemBox/itemBox.stories.tsx
  components/itemBox/itemBox.tsx
Labels: feature

#52 프로젝트 초기 세팅 (axios, tanstack, sitemap, robots, meta ...)
  .eslintrc.json
  api/axios/common.apis.ts
  api/axios/instance/instance.apis.ts
  api/axios/instance/instance.helpers.ts
  api/axios/instance/instance.types.ts
  api/tanstack/queryHydrate.context.tsx
  api/tanstack/tanstack.helpers.ts
  api/tanstack/tanstack.types.ts
  api/tanstack/tanstackProvider.context.tsx
  app/(main)/page.tsx
  app/_meta/index.ts
  app/layout.tsx
  app/not-found.tsx
  app/robots.ts
  app/sitemap.ts
  package-lock.json
  package.json
Labels: chore, feature

#54 공통 컴포넌트 - ItemBtn 제작
  components/itemBtn/itemBtn.module.scss
  components/itemBtn/itemBtn.stories.tsx
  components/itemBtn/itemBtn.tsx
  components/itemBtn/itemBtn.types.ts
Labels: feature

#56 공통 컴포넌트 formBox 제작
  components/commonBtn/commonBtn.tsx
  components/commonBtn/commonBtn.types.ts
  components/formBox/backBtn.module.scss
  components/formBox/backBtn.stories.ts
  components/formBox/backBtn.tsx
  components/formBox/backBtn.types.ts
  components/formBox/formBox.module.scss
  components/formBox/formBox.stories.ts
  components/formBox/formBox.tsx
  components/formBox/formBox.types.ts
  components/simpleLayout/layoutBtn.module.scss
  components/simpleLayout/layoutBtn.tsx
  components/simpleLayout/simpleLayout.module.scss
  package-lock.json
  package.json
  public/images/back.svg
  public/images/defaultCharacter.png
Labels: feature

#58 Fab 버튼 구현(PC)
  components/fab/circleButton.module.scss
  components/fab/fab.module.scss
  components/fab/fab.stories.tsx
  components/fab/fab.tsx
  components/fab/fabForDf.stories.tsx
  components/fab/fabForDf.tsx
  package-lock.json
  package.json
Labels: chore, feature

#61 commonBtn 컴포넌트 mo UI 추가
  components/commonBtn/commonBtn.module.scss
Labels: feature

#62 공통컴포넌트-gnb 구현
  app/layout.tsx
  components/formBox/formBox.tsx
  components/gnb/gnb.module.scss
  components/gnb/gnb.stories.ts
  components/gnb/gnb.tsx
  components/gnb/gnbChip.module.scss
  components/gnb/gnbChip.stories.ts
  components/gnb/gnbChip.tsx
  components/gnb/gnbChip.types.ts
  components/simpleLayout/layoutBtn.module.scss
  hooks/useBreakpoint.hooks.ts
  types/user.enum.ts
Labels: feature

#66 rename: editBtn 폴더명 변경
  components/editBtn/editBtn.module.scss
  components/editBtn/editBtn.stories.ts
  components/editBtn/editBtn.tsx
  components/editBtn/editBtn.types.ts
Labels: chore

#63 Feature/implement modal layout/#59
  components/modalLayout/characterModalLayout.module.scss
  components/modalLayout/characterModalLayout.stories.tsx
  components/modalLayout/characterModalLayout.tsx
  components/modalLayout/characterModalLayout.types.ts
  components/modalLayout/contentModalLayout.module.scss
  components/modalLayout/contentModalLayout.stories.tsx
  components/modalLayout/contentModalLayout.tsx
  components/modalLayout/contentModalLayout.types.ts
  components/modalLayout/modalLayout.module.scss
  components/modalLayout/modalLayout.stories.tsx
  components/modalLayout/modalLayout.tsx
  components/modalLayout/modalLayout.types.ts
Labels: feature

#67 마이페이지 내 질답 card 컴포넌트 구현
  components/descriptionCard/descriptionCard.module.scss
  components/descriptionCard/descriptionCard.stories.tsx
  components/descriptionCard/descriptionCard.tsx
  components/descriptionCard/descriptionCard.types.ts
Labels: feature

#69 CircleButton 컴포넌트 모바일 반응형 구현
  components/fab/circleButton.module.scss
  components/fab/circleButton.tsx
Labels: feature

#71 기능 구현 - Radar Chart 모바일에서의 회전 및 확대/축소 기능
  components/radarChart/helpers/axis.helpers.ts
  components/radarChart/helpers/radarChart.helpers.ts
  components/radarChart/radarChart.tsx
  components/radarChart/radarChartContainer.tsx
Labels: feature

#74 storybook 반응형 config 추가
  .storybook/preview.ts
Labels: hotfix

#80 chore - recoil 세팅
  app/layout.tsx
  package-lock.json
  package.json
  store/recoilRootWrapper.tsx
Labels: chore

#83 마이페이지 기본 / 꿀팁 카드 컴포넌트 구현
  components/descriptionCard/descriptionCard.stories.tsx
  components/descriptionCard/descriptionCard.tsx
  components/descriptionCard/descriptionCard.types.ts
  components/descriptionCard/myDescriptionCard.module.scss
  components/descriptionCard/myDescriptionCard.stories.tsx
  components/descriptionCard/myDescriptionCard.tsx
  components/descriptionCard/othersDescriptionCard.module.scss
  components/descriptionCard/othersDescriptionCard.stories.tsx
  components/descriptionCard/othersDescriptionCard.tsx
  components/descriptionCard/othersDescriptionCard.types.ts
Labels: feature

#78 UI 구현 - Radar Chart 컴포넌트 제작 완료 (각 페이지별로 스토리 확인 가능)
  api/axios/instance/instance.apis.ts
  app/api/mock-radar/route.ts
  components/radarChart/defaultPolygon.stories.ts
  components/radarChart/draggablePolygon.stories.ts
  components/radarChart/helpers/axis.helpers.ts
  components/radarChart/helpers/radarChart.helpers.ts
  components/radarChart/radar-mock.apis.ts
  components/radarChart/radarChart.module.scss
  components/radarChart/radarChart.tsx
  components/radarChart/radarChart.types.ts
  components/radarChart/radarChartContainer.module.scss
  components/radarChart/radarChartContainer.stories.ts
  components/radarChart/radarChartContainer.tsx
  components/radarChart/radarChartFetcher.tsx
Labels: feature

#85 keywordBtn 컴포넌트 구현
  components/keywordBtn/keywordBtn.module.scss
  components/keywordBtn/keywordBtn.stories.tsx
  components/keywordBtn/keywordBtn.tsx
  components/keywordBtn/keywordBtn.types.ts
Labels: feature

#87 footer 컴포넌트 구현
  app/layout.tsx
  components/footer/footer.module.scss
  components/footer/footer.stories.ts
  components/footer/footer.tsx
  public/images/email-grey.svg
  public/images/facebook-grey.svg
  public/images/instagram-grey.svg
Labels: feature

#91 SignIn 페이지 UI 구현
  app/(auth)/signin/page.tsx
  components/signIn/buttonHoverTapAnimation.tsx
  components/signIn/signIn.module.scss
  components/signIn/signIn.tsx
  components/signIn/signinSocialContainer.tsx
  public/images/signin-bat-left-bottom.png
  public/images/signin-bat-left-top.png
  public/images/signin-bat-right-middle.png
  public/images/signin-castle.png
  public/images/signin-ghost-left-middle.png
  public/images/signin-ghost-right-bottom.png
  public/images/signin-github.svg
  public/images/signin-google.svg
  public/images/signin-kakao.svg
  public/images/signin-our-story-btn.svg
  public/images/signin-title.png
Labels: feature

#98 custom useFunnel 훅 구현
  hooks/useFunnel.tsx
Labels: feature

#100 Radar 컴포넌트 버튼 UI 및 애니메이션 수정
  components/radarChart/radarChartContainer.module.scss
  components/radarChart/radarChartContainer.tsx
Labels: refactor

#109 MyDescriptionCard 수정 hotfix
  components/descriptionCard/myDescriptionCard.module.scss
  components/descriptionCard/myDescriptionCard.tsx
  components/descriptionCard/myDescriptionCard.types.ts
Labels: hotfix

#105 기능 구현 - 우리들의 페이지에 들어갈만한 애니메이션 예제 작성
  components/scrollMotion/normalTextAndRect/normalTextAndRect.stories.ts
  components/scrollMotion/normalTextAndRect/normalTextAndRect.tsx
  components/scrollMotion/rightSticky/featureCard.tsx
  components/scrollMotion/rightSticky/featureStore.store.tsx
  components/scrollMotion/rightSticky/featureTitle.tsx
  components/scrollMotion/rightSticky/rightSticky.module.scss
  components/scrollMotion/rightSticky/rightSticky.stories.ts
  components/scrollMotion/rightSticky/rightSticky.tsx
  components/scrollMotion/scrollSlides/scrollSlides.module.scss
  components/scrollMotion/scrollSlides/scrollSlides.stories.ts
  components/scrollMotion/scrollSlides/scrollSlides.tsx
  components/scrollMotion/shared/mockHeight.tsx
  components/scrollMotion/shared/mockRect.tsx
  components/scrollMotion/shared/mockText.tsx
  helpers/throttle.helpers.ts
Labels: feature

#103 등록 완료 시 축하 애니메이션 구현 (Confetti Button)
  components/confettiCanvasBtn/confetti.helpers.ts
  components/confettiCanvasBtn/confettiCanvasBtn.module.scss
  components/confettiCanvasBtn/confettiCanvasBtn.stories.ts
  components/confettiCanvasBtn/confettiCanvasBtn.tsx
  components/confettiCanvasBtn/exampleBtn.tsx
  components/confettiCanvasBtn/models/confetto.models.ts
  components/confettiCanvasBtn/models/sequin.models.ts
Labels: feature

#113 마이페이지 구현 - 1
  app/(main)/[userType]/my-page/page.tsx
  components/descriptionCard/othersDescriptionCard.tsx
  components/descriptionCard/othersDescriptionCard.types.ts
  components/linkBtn/linkBtn.module.scss
  components/linkBtn/linkBtn.tsx
  components/manualBox/manualBox.tsx
  components/manualBox/manualBox.types.ts
  components/manualBox/myManualLayout.module.scss
Labels: feature

#112 resize 이벤트에 throttle 적용 및 delay 수정
  components/confettiCanvasBtn/confettiCanvasBtn.tsx
  components/scrollMotion/scrollSlides/scrollSlides.tsx
Labels: refactor

#116 기능 구현 - 우리들 페이지 애니메이션, 새로운 페이지 등장 모션
  components/scrollMotion/rightSticky/featureCard.tsx
  components/scrollMotion/rightSticky/featureDetail.module.scss
  components/scrollMotion/rightSticky/featureDetail.tsx
  components/scrollMotion/rightSticky/featureStore.store.tsx
  components/scrollMotion/rightSticky/featureTitle.tsx
  components/scrollMotion/rightSticky/rightSticky.module.scss
  components/scrollMotion/rightSticky/rightSticky.stories.tsx
  components/scrollMotion/rightSticky/rightSticky.tsx
Labels: feature

#115 My Manual Page Ui 제작 및 Funnel 적용
  components/characterBox/characterBox.tsx
  components/characterBox/characterBox.types.ts
  components/commonBtn/commonBtn.tsx
  components/commonInput/input.module.scss
  components/commonInput/input.tsx
  components/commonInput/input.types.ts
  components/descriptionCard/myDescriptionCard.helpers.tsx
  components/descriptionCard/myDescriptionCard.module.scss
  components/descriptionCard/myDescriptionCard2.tsx
  components/formBox/formBox.module.scss
  components/inventory/inventory.module.scss
  components/inventory/inventory.tsx
  components/inventory/inventoryItemBoxList/inventoryItemBoxList.tsx
  components/keywordBtn/keywordBtn.module.scss
  components/keywordBtnList/keywordBtnList.module.scss
  components/keywordBtnList/keywordBtnList.tsx
  components/keywordBtnList/keywordBtnList.types.ts
  components/makeMyManual/makeMyManual.module.scss
  components/makeMyManual/makeMyManual.tsx
  components/makeMyManual/makeMyManual.types.ts
  components/makeMyManual/store/makeMyManual.atom.tsx
  components/makeMyManual/store/originKeywordPercents.selecter.ts
  components/myDescriptionCardList/myDescriptionCardList.module.scss
  components/myDescriptionCardList/myDescriptionCardList.tsx
  hooks/useFunnel.tsx
  public/data/inventory.mockdata.json
Labels: feature

#119 radar chart container setter prop 추가
  components/radarChart/radarChart.types.ts
  components/radarChart/radarChartContainer.tsx
  components/radarChart/radarChartFetcher.tsx
Labels: hotfix

#121 signin을 홈페이지로 변경
  app/(auth)/signin/page.tsx
  app/(main)/page.tsx
Labels: hotfix

#123 gnb 스크롤 이벤트 추가
  components/gnb/gnb.module.scss
  components/gnb/gnb.tsx
  hooks/useScrolledState.ts
Labels: feature

#126 circleBtn, ghostBtn 컴포넌트 제작
  components/circleBtn/circleBtn.module.scss
  components/circleBtn/circleBtn.stories.tsx
  components/circleBtn/circleBtn.tsx
  components/circleBtn/circleBtn.types.ts
  components/ghostBtn/ghostBtn.module.scss
  components/ghostBtn/ghostBtn.stories.tsx
  components/ghostBtn/ghostBtn.tsx
  components/ghostBtn/ghostBtn.types.ts
  public/images/ghost-btn.png
Labels: feature

#127 use-funnel history 기능 구현
  components/makeMyManual/makeMyManual.tsx
  hooks/useFunnel.tsx
Labels: feature

#130 Radar 컴포넌트 버그 수정
  components/radarChart/radarChart.types.ts
  components/radarChart/radarChartContainer.tsx
  components/radarChart/radarChartFetcher.tsx
Labels: hotfix, bug

#131 소셜 로그인 / 로그아웃 api 핸들러 제작
  api/axios/common.apis.ts
  api/axios/requestHandler/auth/auth.types.ts
  api/axios/requestHandler/auth/google.apis.ts
  api/axios/requestHandler/auth/kakao.apis.ts
  api/axios/requestHandler/auth/logout.apis.ts
Labels: feature

#135 Feature/assemble my page 2/#114
  app/(main)/[userType]/my-page/page.tsx
  components/characterBox/characterBox.module.scss
  components/characterBox/characterBox.tsx
  components/characterBox/characterBox.types.ts
  components/contentsWrapper/contentWrapper.module.scss
  components/contentsWrapper/contentWrapper.tsx
  components/descriptionCard/myDescriptionCard.module.scss
  components/descriptionCard/othersDescriptionCard.stories.tsx
  components/descriptionCard/othersDescriptionCard.tsx
  components/descriptionCard/othersDescriptionCard.types.ts
  components/fab/circleButton.module.scss
  components/fab/circleButton.tsx
  components/fab/fab.module.scss
  components/manualBox/manualBox.module.scss
  components/manualBox/manualBox.tsx
  components/manualBox/manualBox.types.ts
  components/profileBox/profileBox.module.scss
  components/profileBox/profileBox.tsx
  components/profileBox/profileBox.types.ts
Labels: feature

#138 마이페이지 handler 및 endpoint 제작 (get/put)
  api/axios/instance/instance.apis.ts
  api/axios/requestHandler/auth/get.apis.ts
  api/axios/requestHandler/auth/google.apis.ts
  api/axios/requestHandler/auth/kakao.apis.ts
  api/axios/requestHandler/auth/logout.apis.ts
  api/axios/requestHandler/auth/post.apis.ts
  api/axios/requestHandler/mypage/get.apis.ts
  api/axios/requestHandler/mypage/mypage.types.ts
  api/axios/requestHandler/mypage/put.apis.ts
  app/api/answers/route.ts
  app/api/jff/character/route.ts
  app/api/jff/mypage/route.ts
  app/api/jff/nickname/route.ts
  app/api/mock-radar/route.ts
  components/radarChart/radar-mock.apis.ts
  public/data/mypage.mockdata.json
Labels: feature

#139 기능 구현 : Radar Chart 내 hover 시 tooltip 구현 및 rotate 대응
  components/radarChart/helpers/radarChart.helpers.ts
Labels: feature, refactor

#146 My manual invalid 적용 및 post 구현
  .eslintrc.json
  api/requestHandler/myManual/postMyManual.api.tsx
  app/(main)/[userType]/my-manual/page.tsx
  app/api/jff/my-manual/route.ts
  components/commonInput/input.module.scss
  components/commonInput/input.tsx
  components/commonInput/input.types.ts
  components/makeMyManual/makeMyManual.api.ts
  components/makeMyManual/makeMyManual.helpers.tsx
  components/makeMyManual/makeMyManual.module.scss
  components/makeMyManual/makeMyManual.tsx
  components/makeMyManual/makeMyManual.types.ts
  components/makeMyManual/makeMyManualFunnel/makeMyManualFunnel.module.scss
  components/makeMyManual/makeMyManualFunnel/makeMyManualFunnel.tsx
  components/makeMyManual/store/makeMyManual.atom.tsx
  components/makeMyManual/store/originKeywordPercents.selecter.ts
  components/myDescriptionCardList/myDescriptionCardList.tsx
  hooks/useFunnel.tsx
  public/data/inventory.mockdata.json
Labels: feature, bug

#140 기능 구현 및 레이아웃 : 우리들의 이야기 페이지 애니메이션
  app/(main)/our-story/page.module.scss
  app/(main)/our-story/page.tsx
  components/ourStorySection/imageSection/imageCard.models.tsx
  components/ourStorySection/imageSection/imageCard.module.scss
  components/ourStorySection/imageSection/imageCard.tsx
  components/ourStorySection/imageSection/imageSection.module.scss
  components/ourStorySection/imageSection/imageSection.tsx
  components/ourStorySection/ourFeature/featureCard.module.scss
  components/ourStorySection/ourFeature/featureCard.tsx
  components/ourStorySection/ourFeature/featureTitle.module.scss
  components/ourStorySection/ourFeature/featureTitle.tsx
  components/ourStorySection/ourFeature/ourFeature.models.tsx
  components/ourStorySection/ourFeature/ourFeature.module.scss
  components/ourStorySection/ourFeature/ourFeature.tsx
  components/ourStorySection/ourIntro/ourIntro.module.scss
  components/ourStorySection/ourIntro/ourIntro.tsx
  components/ourStorySection/shared/store/featureStore.store.tsx
  components/scrollMotion/rightSticky/featureTitle.tsx
  components/scrollMotion/rightSticky/rightSticky.module.scss
  public/images/hero-mobile.png
Labels: feature

#143 TJNS 경우의 수 추가 (Radar Chart Container)
  components/radarChart/radarChartContainer.tsx
Labels: hotfix, bug

#145 마이페이지 공유 기능 구현 -페이스북 공유, 클립보드 복사
  services/clipboard.helpers.ts
  services/facebook.helpers.ts
Labels: feature

#149 Inventory GET 구현 및 isEdit 추가
  api/axios/requestHandler/inventory/inventory.api.ts
  app/api/jff/characterItems/route.ts
  app/api/jff/my-manual/route.ts
  components/inventory/inventory.tsx
  components/keywordBtnList/keywordBtnList.tsx
  components/makeMyManual/makeMyManual.tsx
  components/myDescriptionCardList/myDescriptionCardList.tsx
  public/data/inventory.mockdata.json
  public/data/my-manual.mockdata.json
Labels: feature, bug

#151 character box에 nickname 추가
  components/characterBox/characterBox.module.scss
  components/keywordBtnList/keywordBtnList.tsx
  components/makeMyManual/makeMyManual.tsx
Labels: feature

#153 타적나사 UI 구현
  api/requestHandler/othersManual/postOthersManual.api.tsx
  app/(main)/[userType]/others-manual/[userId]/page.tsx
  app/api/others-manual/route.ts
  components/characterBox/characterBox.module.scss
  components/circleBtn/circleBtn.module.scss
  components/circleBtn/circleBtn.tsx
  components/descriptionCard/myDescriptionCard.module.scss
  components/descriptionCard/myDescriptionCard2.tsx
  components/makeMyManual/makeMyManual.module.scss
  components/makeOthersDescriptionCardList/makeOthersDescriptionCardList.module.scss
  components/makeOthersDescriptionCardList/makeOthersDescriptionCardList.tsx
  components/makeOthersManual/makeOthersManual.api.ts
  components/makeOthersManual/makeOthersManual.module.scss
  components/makeOthersManual/makeOthersManual.tsx
  components/makeOthersManual/makeOthersManualFunnel/makeOthersManualFunnel.module.scss
  components/makeOthersManual/makeOthersManualFunnel/makeOthersManualFunnel.tsx
  components/makeOthersManual/modalDescriptionCardList/modalDescriptionCardList.module.scss
  components/makeOthersManual/modalDescriptionCardList/modalDescriptionCardList.tsx
  components/makeOthersManual/othersCharacterBox/othersCharacterBox.module.scss
  components/makeOthersManual/othersCharacterBox/othersCharacterBox.tsx
  components/makeOthersManual/store/makeOthersManual.atom.tsx
  components/modalLayout/contentModalLayout2.module.scss
  components/modalLayout/contentModalLayout2.tsx
  components/modalLayout/contentModalLayout2.types.ts
  public/data/others-manual.mockdata2.json
  public/images/character-base.svg
  public/images/character-body-1.svg
  public/images/character-expression-1.svg
  public/images/character-face-1.svg
  utils/transformData.ts
Labels: feature

#156 타적나사 라우팅 수정
  app/(main)/[userType]/others-manual/page.tsx
  app/api/jff/others-manual/route.ts
  components/makeOthersManual/makeOthersManual.api.ts
  components/makeOthersManual/makeOthersManual.tsx
Labels: refactor

#158 카카오 소셜 공유하기 기능 구현
  app/layout.tsx
  services/clipboard.helpers.ts
  services/facebook.helpers.ts
  services/kakao.helpers.ts
Labels: feature, refactor

#161 타적나사 라우팅 수정
  app/(main)/[userType]/others-manual/[userId]/page.tsx
  app/(main)/[userType]/others-manual/page.tsx
  app/api/others-manual/route.ts
  components/makeOthersDescriptionCardList/makeOthersDescriptionCardList.tsx
  components/makeOthersManual/makeOthersManual.api.ts
  components/makeOthersManual/makeOthersManual.tsx
  components/makeOthersManual/makeOthersManualFunnel/makeOthersManualFunnel.tsx
  components/makeOthersManual/modalDescriptionCardList/modalDescriptionCardList.tsx
  components/makeOthersManual/othersCharacterBox/othersCharacterBox.tsx
  public/data/others-manual.mockdata2.json
Labels: hotfix, refactor, bug

#154 my page manual edit api 구현
  api/axios/requestHandler/inventory/inventory.api.ts
  api/axios/requestHandler/myManual/getMyManualRegister.api.tsx
  api/axios/requestHandler/myManual/myManual.types.ts
  api/axios/requestHandler/myManual/postMyManual.api.tsx
  app/(main)/[userType]/my-manual/page.tsx
  app/(main)/[userType]/my-page/page.tsx
  components/characterBox/characterBox.types.ts
  components/commonInput/input.module.scss
  components/commonInput/input.tsx
  components/descriptionCard/myDescriptionCard.tsx
  components/inventory/inventory.tsx
  components/keywordBtnList/keywordBtnList.tsx
  components/makeMyManual/makeMyManual.api.ts
  components/makeMyManual/makeMyManual.tsx
  components/makeMyManual/makeMyManual.types.ts
  components/makeMyManual/makeMyManualFunnel/makeMyManualFunnel.tsx
  components/makeOthersManual/modalDescriptionCardList/modalDescriptionCardList.tsx
  components/manualBox/manualBox.tsx
  components/manualBox/manualBox.types.ts
  components/modalLayout/contentModalLayout.module.scss
  components/myDescriptionCardList/myDescriptionCardList.tsx
  components/profileBox/profileBox.tsx
  helpers/validationRule.helpers.ts
Labels: feature

#162 axios instance baseURL 변경 및 로컬 rewrites 적용
  api/axios/instance/instance.apis.ts
  next.config.js
Labels: bug

#167 id number로 변경
  api/axios/requestHandler/mypage/mypage.types.ts
  api/axios/requestHandler/mypage/put.apis.ts
  api/requestHandler/othersManual/postOthersManual.api.tsx
  app/(main)/[userType]/my-page/page.tsx
  app/(main)/[userType]/others-manual/page.tsx
  app/api/jff/others-manual/route.ts
  components/descriptionCard/myDescriptionCard.tsx
  components/descriptionCard/myDescriptionCard2.tsx
  components/descriptionCard/othersDescriptionCard.stories.tsx
  components/descriptionCard/othersDescriptionCard.types.ts
  components/inventory/inventory.types.ts
  components/makeMyManual/makeMyManual.helpers.tsx
  components/makeMyManual/makeMyManual.types.ts
  components/makeOthersDescriptionCardList/makeOthersDescriptionCardList.tsx
  components/makeOthersManual/makeOthersManual.api.ts
  components/makeOthersManual/makeOthersManual.tsx
  components/makeOthersManual/makeOthersManual.type.ts
  components/makeOthersManual/makeOthersManualFunnel/makeOthersManualFunnel.tsx
  components/makeOthersManual/modalDescriptionCardList/modalDescriptionCardList.tsx
  components/makeOthersManual/othersCharacterBox/othersCharacterBox.tsx
  components/manualBox/manualBox.types.ts
  public/data/inventory.mockdata.json
  public/data/my-manual.mockdata.json
  public/data/mypage.mockdata.json
  public/data/others-manual.mockdata2.json
Labels: hotfix, bug

#164 inventory id 저장으로 수정
  api/axios/requestHandler/myManual/postMyManual.api.tsx
  api/axios/requestHandler/mypage/get.apis.ts
  api/axios/requestHandler/mypage/mypage.types.ts
  app/(main)/[userType]/my-page/page.tsx
  components/descriptionCard/myDescriptionCard.tsx
  components/fab/fab.tsx
  components/inventory/inventoryItemBoxList/inventoryItemBoxList.tsx
  components/itemBox/itemBox.stories.tsx
  components/itemBox/itemBox.tsx
  components/makeMyManual/makeMyManual.tsx
  components/makeMyManual/makeMyManual.types.ts
  components/makeMyManual/store/makeMyManual.atom.tsx
  components/manualBox/manualBox.tsx
  components/manualBox/manualBox.types.ts
  components/myDescriptionCardList/myDescriptionCardList.tsx
  components/profileBox/profileBox.tsx
  components/profileBox/profileBox.types.ts
Labels: bug

#172 Bug/change idtype/#165
  app/(main)/[userType]/others-manual/page.tsx
  app/api/jff/others-manual/route.ts
  components/makeOthersDescriptionCardList/makeOthersDescriptionCardList.tsx
  components/makeOthersManual/makeOthersManual.api.ts
  components/makeOthersManual/makeOthersManual.tsx
  components/makeOthersManual/makeOthersManual.type.ts
  components/makeOthersManual/makeOthersManualFunnel/makeOthersManualFunnel.tsx
  components/makeOthersManual/modalDescriptionCardList/modalDescriptionCardList.tsx
  components/makeOthersManual/othersCharacterBox/othersCharacterBox.tsx
  public/data/others-manual.mockdata.json
Labels: hotfix, bug

#173 Feature/my manual progressbar jff/#170
  app/api/JFF/character/route.ts
  app/api/JFF/characterItems/route.ts
  app/api/JFF/my-manual/route.ts
  app/api/JFF/mypage/route.ts
  app/api/JFF/nickname/route.ts
  app/api/JFF/others-manual/route.ts
  components/makeMyManual/makeMyManual.module.scss
  components/makeMyManual/makeMyManual.tsx
  components/progressBar/progressBar.module.scss
Labels: feature, bug

#177 소셜 인증 로직 구현 및 미들웨어 쿠키 주입 적용
  api/axios/common.apis.ts
  api/axios/instance/instance.apis.ts
  api/axios/instance/instance.types.ts
  components/signIn/signinSocialContainer.tsx
  middleware.ts
  next.config.js
Labels: hotfix, feature

#182 마이페이지 api 구현 완료, data type 수정 완료
  api/axios/requestHandler/mypage/mypage.types.ts
  api/axios/requestHandler/mypage/put.apis.ts
  app/(main)/[userType]/my-page/page.tsx
  components/manualBox/manualBox.module.scss
  components/profileBox/profileBox.tsx
  public/data/mypage.mockdata.json
Labels: feature, bug

#187 이미지 로딩 위아래 움직임 기능 구현 (현재 이미지는 mock)
  app/(main)/henry/layout.tsx
  components/loadingImg/imageLoader.module.scss
  components/loadingImg/imageLoader.tsx
  components/loadingImg/imageLoaderWrapper.tsx
  public/images/loading-mock-img.svg
Labels: feature

#188 Gnb 로그아웃 기능 구현 && axios interceptors에 Refresh 추가
  api/axios/instance/instance.apis.ts
  api/axios/requestHandler/auth/post.apis.ts
  components/gnb/gnb.tsx
Labels: feature

#190 Radar 컴포넌트 fade-out 애니메이션 제거
  app/(main)/henry/layout.tsx
  components/loadingImg/imageLoader.tsx
  components/radarChart/helpers/radarChart.helpers.ts
Labels: refactor

#193 미들웨어 구현 1 - 홈페이지 권한 처리
  components/gnb/gnb.tsx
  middleware.ts
Labels: feature, refactor

#194 버튼, 캐릭터 애니메이션 구현
  api/axios/requestHandler/othersManual/getOthersManual.api.tsx
  api/axios/requestHandler/othersManual/postOthersManual.api.tsx
  api/requestHandler/othersManual/postOthersManual.api.tsx
  app/(main)/[userType]/others-manual/page.tsx
  components/characterBox/characterBox.module.scss
  components/characterBox/characterBox.tsx
  components/circleBtn/circleBtn.module.scss
  components/commonBtn/commonBtn.module.scss
  components/commonBtn/commonBtn.stories.ts
  components/commonBtn/commonBtn.tsx
  components/commonBtn/commonBtn.types.ts
  components/makeOthersDescriptionCardList/makeOthersDescriptionCardList.tsx
  components/makeOthersManual/makeOthersManual.module.scss
  components/makeOthersManual/makeOthersManual.tsx
  components/makeOthersManual/makeOthersManualFunnel/makeOthersManualFunnel.module.scss
  components/makeOthersManual/makeOthersManualFunnel/makeOthersManualFunnel.tsx
  components/makeOthersManual/modalDescriptionCardList/modalDescriptionCardList.tsx
  components/makeOthersManual/othersCharacterBox/othersCharacterBox.tsx
  components/modalLayout/contentModalLayout2.module.scss
  styles/_mixin.scss
Labels: feature, refactor

#195 FAB 떠다니는 애니메이션 + 버튼 우하단 그림자 구현
  components/fab/circleButton.module.scss
  components/fab/circleButton.tsx
  components/fab/circleButton.types.ts
  components/fab/fab.module.scss
  components/fab/fab.tsx
  components/fab/fabForDf.module.scss
  components/fab/fabForDf.tsx
Labels: feature

#198 마이페이지 api와 데이터 type 수정
  api/axios/requestHandler/mypage/get.apis.ts
  api/axios/requestHandler/mypage/mypage.types.ts
  app/(main)/[userType]/my-page/page.tsx
Labels: bug

#202 Gnb path에 따른 ui 변경 로직 추가
  components/gnb/gnb.helpers.ts
  components/gnb/gnb.tsx
Labels: refactor

#206 마우스 애니메이션 구현
  app/layout.tsx
  components/ghostCursor/ghostCursor.helpers.ts
  components/ghostCursor/ghostCursor.module.scss
  components/ghostCursor/ghostCursor.tsx
  components/ghostCursor/ghostCursor.types.ts
  components/ghostCursor/ghostCursorController.stories.tsx
  components/ghostCursor/ghostCursorController.tsx
Labels: feature

#207 FAB 관련 story title, args 수정
  components/fab/circleButton.stories.ts
  components/fab/fab.stories.tsx
  components/fab/fabForDf.stories.tsx
Labels: refactor

#208 마우스 애니메이션 제거
  app/layout.tsx
Labels: hotfix

#210 로그아웃 endpoint 수정
  api/axios/requestHandler/auth/post.apis.ts
Labels: hotfix

#215 마이페이지 API 엔드포인트 수정, body 수정
  api/axios/requestHandler/mypage/get.apis.ts
  api/axios/requestHandler/mypage/put.apis.ts
Labels: refactor

#212 my-manual 미들웨어
  middleware.ts
Labels: feature

#218 Feature/refactor my page api/#211
  api/axios/requestHandler/mypage/mypage.types.ts
  components/profileBox/profileBox.tsx
  components/profileBox/profileBox.types.ts
Labels: feature, refactor

#220 radar 초기값 문제 수정
  components/radarChart/helpers/radarChart.helpers.ts
  components/radarChart/radarChartContainer.tsx
Labels: hotfix

#222 홈페이지 제외 마우스 유령 추가
  app/(main)/[userType]/layout.tsx
  app/(main)/our-story/layout.tsx
  components/ghostCursor/ghostCursorController.tsx
Labels: feature

#217 Inventory Animaion 적용
  components/characterBox/characterBox.module.scss
  components/characterBox/characterBox.tsx
  components/itemBox/itemBox.tsx
  components/itemBtn/itemBtn.tsx
Labels: feature

#226 프로젝트 썸네일 추가
  app/_meta/index.ts
  services/kakao.helpers.ts
Labels: hotfix

#219 slide 애니메이션 추가 및 타적나사 데이터 타입 변경
  api/axios/requestHandler/othersManual/getOthersManual.api.tsx
  api/axios/requestHandler/othersManual/postOthersManual.api.tsx
  app/(main)/[userType]/others-manual/page.tsx
  components/commonBtn/commonBtn.tsx
  components/commonInput/input.tsx
  components/formBox/formBox.module.scss
  components/makeOthersDescriptionCardList/makeOthersDescriptionCardList.tsx
  components/makeOthersManual/makeOthersManual.tsx
  components/makeOthersManual/makeOthersManualFunnel/makeOthersManualFunnel.module.scss
  components/makeOthersManual/makeOthersManualFunnel/makeOthersManualFunnel.tsx
  components/makeOthersManual/modalDescriptionCardList/modalDescriptionCardList.tsx
  components/makeOthersManual/othersCharacterBox/othersCharacterBox.tsx
  components/makeOthersManual/store/makeOthersManual.atom.tsx
  hooks/useFunnelwithNoQuery.tsx
  styles/_mixin.scss
Labels: feature, bug

#235 설명서 수정 모달 submit 시 refresh 안 되는 문제 해결
  components/manualBox/manualBox.tsx
Labels: hotfix

#232 FAB 공유 기능 추가
  components/fab/circleButton.tsx
  components/fab/circleButton.types.ts
  components/fab/fab.tsx
Labels: feature, refactor

#237 DF 시도해보기 버튼 주석 처리
  app/(main)/[userType]/my-page/page.tsx
Labels: bug

#238 my manual animation 적용
  components/makeMyManual/makeMyManual.tsx
  components/makeMyManual/makeMyManualFunnel/makeMyManualFunnel.module.scss
  components/makeMyManual/makeMyManualFunnel/makeMyManualFunnel.tsx
  components/makeOthersManual/makeOthersManual.tsx
Labels: feature

#240 my manual routing 처리
  api/axios/requestHandler/myManual/myManual.types.ts
  api/axios/requestHandler/myManual/postMyManual.api.tsx
  components/makeMyManual/makeMyManual.tsx
Labels: feature

#245 마이페이지 token 없을 경우 데이터 불러오는 함수 수정
  api/axios/requestHandler/mypage/get.apis.ts
  app/(main)/[userType]/my-page/page.tsx
Labels: hotfix, bug

#247 Gnb 수정
  app/layout.tsx
  components/gnb/gnb.helpers.ts
  components/gnb/gnb.tsx
  components/gnb/gnbRight.tsx
Labels: refactor

#248 CopyToast 구현 및 FAB에 적용
  components/copyToast/copyToast.module.scss
  components/copyToast/copyToast.stories.tsx
  components/copyToast/copyToast.tsx
  components/fab/fab.tsx
  services/clipboard.helpers.ts
Labels: feature

#250 파비콘 등록
  app/_meta/index.ts
  public/images/favicon.png
Labels: feature

#253 마우스 애니메이션 분리 (전체 => only mypage)
  app/(main)/[userType]/layout.tsx
  app/(main)/[userType]/my-page/layout.tsx
Labels: bug

#255 마이페이지 타인 데이터 고려 로직 추가
  app/(main)/[userType]/my-page/page.tsx
Labels: refactor

#256 전역 스크롤 ui 수정
  styles/global.scss
Labels: refactor

#258 버튼 로딩 애니메이션 및 타적나사 userType 에러처리 추가
  api/axios/requestHandler/othersManual/getOthersManual.api.tsx
  app/(main)/[userType]/others-manual/layout.tsx
  app/(main)/[userType]/others-manual/page.tsx
  components/commonBtn/commonBtn.module.scss
  components/commonBtn/commonBtn.tsx
  components/commonBtn/commonBtn.types.ts
  components/makeOthersDescriptionCardList/makeOthersDescriptionCardList.tsx
  components/makeOthersManual/makeOthersManual.tsx
  components/makeOthersManual/makeOthersManualFunnel/makeOthersManualFunnel.tsx
  components/makeOthersManual/modalDescriptionCardList/modalDescriptionCardList.tsx
  components/makeOthersManual/othersCharacterBox/othersCharacterBox.tsx
  styles/_mixin.scss
Labels: feature, bug

#260 placeholder box 구현
  components/manualBox/manualBox.module.scss
  components/manualBox/manualBox.tsx
  components/manualBox/placeholderBox.module.scss
  components/manualBox/placeholderBox.tsx
Labels: feature, refactor

#259 Radar chart 최소값 설정
  components/radarChart/helpers/radarChart.helpers.ts
  components/radarChart/radarChartContainer.tsx
Labels: bug

#263 마이페이지 undefined Error 처리
  app/(main)/[userType]/my-page/page.tsx
Labels: bug

#264 마이페이지 커서 제거 및 버튼 타입으로 변경
  components/manualBox/manualBox.module.scss
  components/manualBox/manualBox.tsx
Labels: refactor

#265 설명서 편집 모달 레이아웃 수정
  components/manualBox/manualBox.module.scss
  components/manualBox/manualBox.tsx
  components/modalLayout/characterModalLayout.module.scss
  components/modalLayout/contentModalLayout.module.scss
  components/modalPortal/modalPortal.module.scss
Labels: bug

#242 my manual server fetch 에러 해결
  api/axios/requestHandler/myManual/getMyManualRegister.api.tsx
  api/axios/requestHandler/myManual/myManual.types.ts
  app/(main)/[userType]/my-manual/page.tsx
  components/keywordBtnList/keywordBtnList.tsx
  components/makeMyManual/makeMyManual.tsx
  components/myDescriptionCardList/myDescriptionCardList.tsx
Labels: bug

#273 토스트 공통컴포넌트, GNB및 타적나사 로딩 추가
  app/(main)/[userType]/layout.tsx
  components/characterBox/characterBox.module.scss
  components/characterBox/characterBox.tsx
  components/commonBtn/commonBtn.tsx
  components/copyToast/copyToast.module.scss
  components/copyToast/copyToast.stories.tsx
  components/copyToast/copyToast.tsx
  components/copyToast/copyToast.types.ts
  components/fab/fab.tsx
  components/gnb/gnbRight.tsx
  components/loadingImg/imageLoader.module.scss
  components/loadingImg/imageLoader.tsx
  components/makeOthersManual/makeOthersManual.tsx
  components/modalLayout/contentModalLayout2.module.scss
  public/images/check.png
  public/images/close.svg
  public/images/error.png
  public/images/loading.svg
Labels: feature, refactor, bug

#277 로그인 버튼 사이즈 수정
  components/signIn/signIn.module.scss
  components/signIn/signinSocialContainer.tsx
Labels: refactor

#278 토스트 임시 실행 코드 제거
  api/axios/requestHandler/myManual/myManual.types.ts
  components/makeOthersManual/makeOthersManual.tsx
Labels: bug

#268 캐릭터 편집 모달 수정
  api/axios/requestHandler/mypage/put.apis.ts
  components/manualBox/manualBox.tsx
  components/modalLayout/characterModalLayout.module.scss
  components/modalLayout/characterModalLayout.stories.tsx
  components/modalLayout/characterModalLayout.tsx
  components/modalLayout/characterModalLayout.types.ts
  components/modalLayout/contentModalLayout.module.scss
  components/profileBox/profileBox.module.scss
  components/profileBox/profileBox.tsx
Labels: bug

#281 Radar Chart 모바일 대응
  components/radarChart/helpers/radarChart.helpers.ts
  components/radarChart/radarChartContainer.tsx
Labels: hotfix, refactor, bug

#283 commonInput 컴포넌트 폰트 사이즈 반응형 추가
  components/commonInput/input.module.scss
Labels: bug

#280 shareUrl 관련 중복 코드 문제 해결
  components/fab/circleButton.tsx
  components/fab/circleButton.types.ts
  components/fab/fab.tsx
Labels: refactor

#284 Revert "shareUrl 관련 중복 코드 문제 해결"
  components/fab/circleButton.tsx
  components/fab/circleButton.types.ts
  components/fab/fab.tsx
Labels: hotfix, bug

#286 profile padding 수정
  app/not-found.tsx
  components/error/error.module.scss
  components/formBox/formBox.module.scss
  components/makeMyManual/makeMyManual.module.scss
  components/makeMyManual/makeMyManual.tsx
  components/profileBox/profileBox.module.scss
Labels: bug

#290 mypage 캐릭터 편집창 레이아웃 수정
  components/modalLayout/characterModalLayout.module.scss
  components/modalPortal/modalPortal.module.scss
  components/profileBox/profileBox.module.scss
Labels: bug

#287 fix my page character 크기
  components/characterBox/characterBox.module.scss
Labels: bug

#289 my manual page titie 및 버튼 수정, My-page characterItems put api 로직 수정
  api/axios/requestHandler/mypage/put.apis.ts
  components/makeMyManual/makeMyManual.tsx
  components/profileBox/profileBox.tsx
Labels: bug

#294 홈페이지에서 우리들의 이야기 버튼 임시 제거 // Gnb href 임시 제거
  components/gnb/gnb.tsx
  components/signIn/signIn.tsx
Labels: hotfix

#299 타적나사 formbox ui 수정
  components/makeOthersManual/makeOthersManual.module.scss
  components/makeOthersManual/makeOthersManual.tsx
Labels: bug

#300 마이페이지 커서 애니메이션 제거
  app/(main)/[userType]/my-page/layout.tsx
Labels: bug

#301 타적나사 질문 닉네임 변경
  components/makeOthersManual/makeOthersDescriptionCard/makeOthersDescriptionCard.tsx
  components/makeOthersManual/makeOthersDescriptionCard/makeOthersDescriptionCardList.module.scss
  components/makeOthersManual/makeOthersDescriptionCard/makeOthersDescriptionCardList.tsx
  components/makeOthersManual/makeOthersManualFunnel/makeOthersManualFunnel.tsx
Labels: bug

#305 OthersDescriptionCard에서 닉네임 부분이 000으로 출력되는 버그를 해결
  app/(main)/[userType]/my-page/page.tsx
  components/manualBox/manualBox.tsx
  components/manualBox/manualBox.types.ts
Labels: bug

#302 마이페이지 로딩 Toast 처리, 성공 시 Toast
  components/manualBox/manualBox.tsx
  components/profileBox/profileBox.tsx
Labels: feature

#309 my manual loading error 처리
  app/(main)/[userType]/my-manual/loading.tsx
  components/makeMyManual/makeMyManual.tsx
Labels: feature

#306 ManualBox title에 nickname 반영
  components/manualBox/manualBox.tsx
Labels: bug

#310 마이페이지 API 에러 핸들링 추가
  app/(main)/[userType]/my-page/error.tsx
  app/(main)/[userType]/my-page/page.tsx
  components/error/mypageError.module.scss
  components/error/mypageError.tsx
  components/manualBox/manualBox.tsx
  components/profileBox/profileBox.tsx
Labels: feature

#314 footer width 조정
  components/footer/footer.module.scss
Labels: bug

#312 hotfix - my manual login routing 및 error 페이지 띄어쓰기 추가
  components/error/error.module.scss
  components/makeMyManual/makeMyManual.tsx
Labels: hotfix, bug

#311 미들웨어 추가 - 본인 others-manual 페이지 접근 금지
  middleware.ts
Labels: feature

#307 초안 - 우리들의 이야기 페이지 제작
  app/(main)/our-story/page.module.scss
  app/(main)/our-story/page.tsx
  components/footer/footer.tsx
  components/ghostCursor/ghostCursorController.tsx
  components/gnb/gnb.tsx
  components/ourStorySection/imageSection/imageCard.models.tsx
  components/ourStorySection/imageSection/imageCard.module.scss
  components/ourStorySection/imageSection/imageCard.tsx
  components/ourStorySection/imageSection/imageSection.module.scss
  components/ourStorySection/imageSection/imageSection.tsx
  components/ourStorySection/ourFeature/currentHeightChecker.tsx
  components/ourStorySection/ourFeature/deleteElement.tsx
  components/ourStorySection/ourFeature/featureCard.module.scss
  components/ourStorySection/ourFeature/featureCard.tsx
  components/ourStorySection/ourFeature/featureTitle.module.scss
  components/ourStorySection/ourFeature/featureTitle.tsx
  components/ourStorySection/ourFeature/leftTitle.module.scss
  components/ourStorySection/ourFeature/leftTitle.tsx
  components/ourStorySection/ourFeature/ourFeature.models.tsx
  components/ourStorySection/ourFeature/ourFeature.module.scss
  components/ourStorySection/ourFeature/ourFeature.tsx
  components/ourStorySection/ourFeature/rightCard.module.scss
  components/ourStorySection/ourFeature/rightCard.tsx
  components/ourStorySection/ourIntro/ourIntro.module.scss
  components/ourStorySection/ourIntro/ourIntro.tsx
  components/ourStorySection/ourPortalToSignin/ourPortalToSignin.module.scss
  components/ourStorySection/ourPortalToSignin/ourPortalToSignin.tsx
  components/ourStorySection/ourPreloader/ourPreloader.helpers.ts
  components/ourStorySection/ourPreloader/ourPreloader.module.scss
  components/ourStorySection/ourPreloader/ourPreloader.tsx
  components/ourStorySection/shared/components/emptyHeight/emptyHeight.tsx
  components/scrollMotion/normalTextAndRect/normalTextAndRect.stories.ts
  components/scrollMotion/normalTextAndRect/normalTextAndRect.tsx
  components/scrollMotion/rightSticky/featureCard.tsx
  components/scrollMotion/rightSticky/featureDetail.module.scss
  components/scrollMotion/rightSticky/featureDetail.tsx
  components/scrollMotion/rightSticky/featureStore.store.tsx
  components/scrollMotion/rightSticky/featureTitle.tsx
  components/scrollMotion/rightSticky/rightSticky.module.scss
  components/scrollMotion/rightSticky/rightSticky.stories.tsx
  components/scrollMotion/rightSticky/rightSticky.tsx
  components/scrollMotion/scrollSlides/scrollSlides.module.scss
  components/scrollMotion/scrollSlides/scrollSlides.stories.ts
  components/scrollMotion/scrollSlides/scrollSlides.tsx
  components/scrollMotion/shared/mockHeight.tsx
  components/scrollMotion/shared/mockRect.tsx
  components/scrollMotion/shared/mockText.tsx
  components/signIn/signIn.tsx
  public/images/os-character-desktop.png
  public/images/os-character-mobile.png
  public/images/os-chart-desktop.png
  public/images/os-chart-mobile.png
  public/images/os-feedback-desktop.png
  public/images/os-feedback-mobile.png
  public/images/os-manual-desktop.png
  public/images/os-manual-mobile.png
  public/images/os-others-desktop.png
  public/images/os-others-mobile.png
  public/images/white-bottom-arrow.png
Labels: feature, refactor

#317 others 모바일에서 나도해보기 버튼 absolute로 변경
  components/circleBtn/circleBtn.module.scss
  components/makeOthersManual/makeOthersManual.module.scss
  components/makeOthersManual/makeOthersManual.tsx
  components/makeOthersManual/makeOthersManualFunnel/makeOthersManualFunnel.tsx
Labels: bug

#320 logo 이미지 변경
  components/gnb/gnb.module.scss
  components/gnb/gnb.tsx
  public/images/logo2.png
Labels: bug

#322 Gnb Route 적용, 로그아웃 에러 처리, MyManual 쿠키 등록 추가
  components/gnb/gnb.tsx
  components/gnb/gnbRight.tsx
  components/makeMyManual/makeMyManual.tsx
  components/ourStorySection/ourPortalToSignin/ourPortalToSignin.tsx
  components/radarChart/radarChartContainer.tsx
Labels: feature, bug

#324 모바일에서 nickname chip 겹치는 문제 해결(임시)
  components/descriptionCard/othersDescriptionCard.module.scss
Labels: hotfix

#323 Radar 스크롤 이벤트 대응
  components/radarChart/helpers/radarChart.helpers.ts
Labels: bug

#325 mobile font size mixin 조정 및 불필요한 컴포넌트 제거
  components/descriptionCard/myDescriptionCard2.tsx
  styles/_mixin.scss
Labels: bug

#327 태블릿 profileBox 레이아웃 깨짐 현상 수정
  components/profileBox/profileBox.module.scss
Labels: hotfix

#328 타적나사 ui 수정
  app/(main)/[userType]/others-manual/page.tsx
  components/makeOthersManual/makeOthersDescriptionCard/makeOthersDescriptionCardList.module.scss
  components/makeOthersManual/makeOthersDescriptionCard/makeOthersDescriptionCardList.tsx
  components/makeOthersManual/makeOthersManual.module.scss
  components/makeOthersManual/makeOthersManual.tsx
  components/makeOthersManual/makeOthersManualFunnel/makeOthersManualFunnel.module.scss
  components/makeOthersManual/othersCharacterBox/othersCharacterBox.module.scss
Labels: hotfix, bug

#329 마이페이지 불필요한 console 코드, 주석 삭제
  app/(main)/[userType]/my-page/page.tsx
  components/manualBox/manualBox.tsx
  components/profileBox/profileBox.tsx
Labels: refactor

#331 Footer href 적용 (페이스북, 인스타그램, 메일)
  components/footer/footer.module.scss
  components/footer/footer.tsx
Labels: refactor

#333 FAB, 나도 해보기 버튼 모바일 위치 조정
  components/fab/fab.module.scss
  components/makeOthersManual/makeOthersManual.module.scss
Labels: hotfix

#336 GA 설치
  app/layout.tsx
  helpers/gtag.js
  tsconfig.json
Labels: feature

#337 hotfix - ga script 위치 이동
  app/layout.tsx
Labels: hotfix, bug

#338 gnb router 수정
  app/layout.tsx
  components/gnb/gnbRight.tsx
Labels: hotfix

#339 미들웨어 수정
  middleware.ts
Labels: hotfix

#340 gnb route 수정
  components/gnb/gnbRight.tsx
  middleware.ts
Labels: hotfix

#341 fix: gnb setter 적용
  components/gnb/gnbRight.tsx
Labels: hotfix

#342 Link 컴포넌트 => useRouter로 변경
  components/gnb/gnb.tsx
  components/gnb/gnbRight.tsx
  components/ourStorySection/ourPortalToSignin/ourPortalToSignin.tsx
Labels: hotfix

#343 fix: router.refresh 추가 적용
  components/gnb/gnb.tsx
  components/gnb/gnbRight.tsx
  components/ourStorySection/ourPortalToSignin/ourPortalToSignin.tsx
Labels: hotfix
